### ISSUE TITLE
Game refuses to load

### ISSUE THREAD

**Issue by noonononnonnoo** [ExtraCrafTX/ExtraDoors#8]
When I start loading the world I want to play on, when the loading cube is filled and says "100%", it just stays there forever. I cannot close the game, nor can I use task manager on it. It is stuck on my computer.

**Comment by ExtraCrafTX** [comment]
Hey, did you by chance have lithium installed as well? I have updated the mod to be compatible with lithium, hopefully this fixes your issue.

If you are still having issues, feel free to open a new issue with more details.
